# Generated by Django 4.2.13 on 2024-06-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('option1', '未完了'), ('option2', '作業中'), ('option3', '完了')], max_length=10, null=True),
        ),
    ]
