# Generated by Django 4.2.13 on 2024-06-24 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='ユーザー名は半角英数字のみで構成してください。', regex='^[a-zA-Z0-9]*$')]),
        ),
    ]
