# Generated by Django 4.2.13 on 2024-06-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
