# Generated by Django 4.2.13 on 2024-06-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_task_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('not_started', '未着手'), ('in_progress', '作業中'), ('completed', '完了')], max_length=15, null=True),
        ),
    ]
