# Generated by Django 5.0.6 on 2024-07-09 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='ユーザー名は半角英数字のみで構成してください。', regex='^[a-zA-Z0-9]*$')], verbose_name='ユーザー名'),
        ),
    ]
