# Generated by Django 5.0.6 on 2024-08-07 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0010_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed'], 'verbose_name_plural': 'タスク'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'ユーザー'},
        ),
    ]
