# Generated by Django 5.0.6 on 2024-08-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0014_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'タスク', 'verbose_name_plural': 'タスク'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
