# Generated by Django 5.0.6 on 2024-08-09 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0015_alter_task_options_remove_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='task',
            name='duedate',
            field=models.DateField(blank=True, null=True, verbose_name='期日'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('option1', '未着手'), ('option2', '作業中'), ('option3', '完了')], max_length=15, null=True, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タスク名'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー名'),
        ),
    ]
